- src: git@github.com:AlexeySetevoi/ansible-clickhouse.git
  scm: git
  version: "1.13"
  name: clickhouse 

- src: git@github.com:drumspb/vector-role
  scm: git
  version: "1.0.0"
  name: vector

- src: git@github.com:drumspb/LightHouse-role
  scm: git
  version: "1.0.0"
  name: LightHouse    