---
- name: Install and configure Clickhouse
  hosts: clickhouse
  become: true
  roles:
    - clickhouse

- name: Install and configure Vector
  hosts: vector
  become: true
  roles:
    - vector

- name: Install and configure LightHouse
  hosts: lighthouse
  become: true
  roles:
    - LightHouse

